---

# This role is the main provision role for each server

# Include default variables
- name: Include default variables
  include_vars: packages.yaml
  become: True

# Include update and upgrade task
# ans installation of systemtools
- name: Include upgrade and installation task
  include: setup_packages.yaml
  become: True

# Provision of local groups
- name: Include provision of local group
  include: provision_group.yaml
  become: True
  vars:
    local_groups:
      home:
        gid: 5000

# Provision of local users
- name: Include provision of local users
  include: provision_user.yaml
  become: True
  vars:
    local_users:
      ansible:
        uid: 10000
        mgmt: True
        groups: "sudo"
      cvonessen:
        uid: 10001
        groups: "home"
      thielking:
        uid: 10002
        groups: "home,sudo"
        mgmt: True
