---
- name: Provision local users
  user:
    append: True
    comment: Normal user
    createhome: True
    groups: "{{ item.value.groups  }}"
    name: "{{ item.key }}"
    shell: /bin/zsh
    state: present
  with_dict: "{{ local_users }}"
