---
- name: Provision local users
  user:
    append: True
    comment: Normal user
    createhome: True
    groups: "{{ item.value.groups  }}"
    name: "{{ item.key }}"
    shell: /bin/zsh
    state: present
  with_dict: "{{ local_users }}"

- name: Debug
  debug: 
    msg: "item.value.git_repo"
  with_dict: "{{ local_users }}"

- name: Load local environment for users from github.com
  git:
    dest: "/home/{{ item.key }}/dots"
    repo: "{{ item.value.git_repo }}"
  become_user: "{{ item.key }}"
  when: item.value.git_repo is defined
  with_dict: "{{ local_users }}"
