---

# Updated all servers
- name: Updating servers
  apt:
    autoremove: True
    update_cache: True
    upgrade: dist
  when: update_apt

# Install common systemtools
- name: Install common systemtools
  apt:
    update_cache: True
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  when: update_apt
