---

# Updated all servers
- name: Updating servers
  apt:
    autoremove: True
    update_cache: True
    upgrade: dist
  when: provisioned

# Install common systemtools
- name: Install common systemtools
  apt:
    update_cache: True
    name: "{{ item }}"
    state: latest
  with_items: "{{ __common_packages|list + common_packages|list }}"
  when: provisioned
